Build everything internally & fix apache builds
robiso/wondercms-builder pull request #2
Opened 2019-03-21 17:23 UTC by notcarbide

Title explains it all. :)

(This was sitting locally for some time now without a commit, so I'm just kinda submitting as-is, but I can also break up the patches if needed.)

2019-03-21 17:52 UTC, NicolasCARPi commented
Thanks I'll have a more thorough look later. As a quick thing that I spotted, use `$(pwd)` instead of ``pwd`` as it is POSIX. See https://stackoverflow.com/questions/9449778/what-is-the-benefit-of-using-instead-of-backticks-in-shell-scripts

2019-03-22 20:21 UTC, notcarbide commented
Excuse the mess haha. Most of what I know about bash (and coding in general) was interpreted from XDA-Developers, so it's all very likely to be all over the place. POSIX probably isn't the only good practice I'm not following ;)

2019-03-22 23:28 UTC, NicolasCARPi requested changes

2019-03-22 23:28 UTC, NicolasCARPi commented on build.sh
> +    echo "Build command failed!"
You should add an "exit 1" here

2019-03-22 23:28 UTC, NicolasCARPi commented on build.sh
> +    echo "Build command failed!"
Instead of having REAL_OPTION, wouldn't it be better to check if ZIP_APPEND is empty?

2019-03-22 23:28 UTC, NicolasCARPi commented on build.sh
> +if [ -n "$1" ]; then
this isn't necessary imho

2019-03-22 23:28 UTC, NicolasCARPi commented on build.sh
> +if [ ! -d "$ZIP_PATH" ]; then
this should be moved after ZIP_PATH declaration

2019-03-25 20:11 UTC, NicolasCARPi approved these changes

2019-03-25 20:11 UTC, merged

2019-03-25 20:11 UTC, NicolasCARPi commented
Thank you!